// <auto-generated />
using System;
using GlobalDisasterManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalDisasterManagement.Migrations
{
    [DbContext(typeof(DisasterDbContext))]
    partial class DisasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalDisasterManagement.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LGAId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LGAId")
                        .HasDatabaseName("IX_Cities_LGAId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cities_Name");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.CityFloodPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prediction")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_CityPredictions_CityId");

                    b.HasIndex("Prediction")
                        .HasDatabaseName("IX_CityPredictions_Prediction");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_CityPredictions_Year");

                    b.HasIndex("CityId", "Year", "Month")
                        .HasDatabaseName("IX_CityPredictions_CityId_Year_Month");

                    b.ToTable("CityPredictions");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.CsvFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UploadDateTime")
                        .HasDatabaseName("IX_CsvFiles_UploadDateTime");

                    b.ToTable("CsvFiles");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.CsvFileCity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<Guid?>("CsvFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CsvFileId");

                    b.ToTable("CsvFileCities");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.DeviceToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Platform")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TopicSubscriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_DeviceTokens_IsActive");

                    b.HasIndex("LastUsedAt")
                        .HasDatabaseName("IX_DeviceTokens_LastUsedAt");

                    b.HasIndex("Platform")
                        .HasDatabaseName("IX_DeviceTokens_Platform");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_DeviceTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_DeviceTokens_UserId");

                    b.ToTable("DeviceTokens");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.DisasterAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcknowledgmentCount")
                        .HasColumnType("int");

                    b.Property<string>("AffectedCities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedCountries")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedLGAs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedRegions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisasterType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvacuationInstructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("MaxLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("MaxLongitude")
                        .HasColumnType("float");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MinLatitude")
                        .HasColumnType("float");

                    b.Property<double?>("MinLongitude")
                        .HasColumnType("float");

                    b.Property<string>("RecommendedActions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelatedAlertIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedIncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SafetyTips")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("ShareCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DisasterType")
                        .HasDatabaseName("IX_DisasterAlerts_DisasterType");

                    b.HasIndex("IssuedAt")
                        .HasDatabaseName("IX_DisasterAlerts_IssuedAt");

                    b.HasIndex("RelatedIncidentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DisasterAlerts_Status");

                    b.ToTable("DisasterAlerts");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.DisasterIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AffectedPeople")
                        .HasColumnType("int");

                    b.Property<string>("AssignedResponders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CasualtiesReported")
                        .HasColumnType("bit");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisasterSpecificData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisasterType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EmergencyResponseTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EmergencyServicesNotified")
                        .HasColumnType("bit");

                    b.Property<bool>("EnvironmentalHazard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int?>("LGAId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<bool>("PeopleTrapped")
                        .HasColumnType("bit");

                    b.Property<string>("PhotoUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PowerOutage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReporterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReporterPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RoadBlocked")
                        .HasColumnType("bit");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("StructuralDamage")
                        .HasColumnType("bit");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrls")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DisasterType")
                        .HasDatabaseName("IX_DisasterIncidents_DisasterType");

                    b.HasIndex("LGAId");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("IX_DisasterIncidents_ReportedAt");

                    b.HasIndex("ReporterId");

                    b.HasIndex("Severity")
                        .HasDatabaseName("IX_DisasterIncidents_Severity");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DisasterIncidents_Status");

                    b.HasIndex("CityId", "Status")
                        .HasDatabaseName("IX_DisasterIncidents_CityId_Status");

                    b.HasIndex("DisasterType", "Status")
                        .HasDatabaseName("IX_DisasterIncidents_DisasterType_Status");

                    b.ToTable("DisasterIncidents");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.DisasterResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AllocatedToIncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AllocatedToShelterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AllocationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPerishable")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastInventoryCheck")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ManagedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("MinimumThreshold")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<bool>("RequiresRefrigeration")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_DisasterResources_Status");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_DisasterResources_Type");

                    b.HasIndex("Type", "Status")
                        .HasDatabaseName("IX_DisasterResources_Type_Status");

                    b.ToTable("DisasterResources");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmergencyHotline")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Is24Hours")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingHours")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ServiceArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<string>("StateProvince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_EmergencyContacts_IsActive");

                    b.HasIndex("ServiceType")
                        .HasDatabaseName("IX_EmergencyContacts_ServiceType");

                    b.ToTable("EmergencyContacts");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.EmergencyShelter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Amenities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentOccupancy")
                        .HasColumnType("int");

                    b.Property<bool>("HasFood")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMedicalFacility")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPower")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSanitation")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSecurity")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWater")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAccessible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("bit");

                    b.Property<int?>("LGAId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_EmergencyShelters_IsActive");

                    b.HasIndex("LGAId");

                    b.HasIndex("CityId", "IsActive")
                        .HasDatabaseName("IX_EmergencyShelters_CityId_IsActive");

                    b.ToTable("EmergencyShelters");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.EvacuationRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<string>("EndAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("EndLatitude")
                        .HasColumnType("float");

                    b.Property<double>("EndLongitude")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("HasLighting")
                        .HasColumnType("bit");

                    b.Property<bool>("HasShelters")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAccessible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int?>("LGAId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastVerified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedShelterIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("MaximumElevationMeters")
                        .HasColumnType("float");

                    b.Property<double?>("MinimumElevationMeters")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteCoordinates")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("StartLatitude")
                        .HasColumnType("float");

                    b.Property<double>("StartLongitude")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Warnings")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LGAId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_EvacuationRoutes_Status");

                    b.HasIndex("CityId", "Status")
                        .HasDatabaseName("IX_EvacuationRoutes_CityId_Status");

                    b.ToTable("EvacuationRoutes");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.LGA", b =>
                {
                    b.Property<int>("LGAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LGAId"));

                    b.Property<string>("LGAName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LGAId");

                    b.HasIndex("LGAName")
                        .HasDatabaseName("IX_LGAs_Name");

                    b.ToTable("LGAs");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.PushNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceTokens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("DisasterAlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisasterIncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<string>("FcmResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SentCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TargetPlatform")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Topic")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PushNotifications_CreatedAt");

                    b.HasIndex("DisasterAlertId")
                        .HasDatabaseName("IX_PushNotifications_DisasterAlertId");

                    b.HasIndex("DisasterIncidentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PushNotifications_Status");

                    b.HasIndex("Topic")
                        .HasDatabaseName("IX_PushNotifications_Topic");

                    b.ToTable("PushNotifications");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.RainfallReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlertTriggered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AlertTriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DailyCumulative")
                        .HasColumnType("float");

                    b.Property<double?>("HourlyCumulative")
                        .HasColumnType("float");

                    b.Property<int>("Intensity")
                        .HasColumnType("int");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double?>("MonthlyCumulative")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<double>("Rainfall")
                        .HasColumnType("float");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("IX_RainfallReadings_SensorId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_RainfallReadings_Timestamp");

                    b.HasIndex("SensorId", "Timestamp")
                        .HasDatabaseName("IX_RainfallReadings_SensorId_Timestamp");

                    b.ToTable("RainfallReadings");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.RainfallSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlertRecipients")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<double>("CollectionArea")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CurrentIntensity")
                        .HasColumnType("int");

                    b.Property<double?>("CurrentRainfall")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CurrentReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DailyRainfall")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("HeavyRainThreshold")
                        .HasColumnType("float");

                    b.Property<double?>("HourlyRainfall")
                        .HasColumnType("float");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LGAId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCommunicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastDataReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("LightRainThreshold")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MeasurementIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ModerateRainThreshold")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PowerSource")
                        .HasColumnType("int");

                    b.Property<double>("Resolution")
                        .HasColumnType("float");

                    b.Property<int>("SensorType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("VeryHeavyRainThreshold")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("IX_RainfallSensors_DeviceId");

                    b.HasIndex("LGAId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_RainfallSensors_Status");

                    b.HasIndex("CityId", "Status")
                        .HasDatabaseName("IX_RainfallSensors_CityId_Status");

                    b.ToTable("RainfallSensors");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.ShelterCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EvacuatedFromAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FamilyMembers")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("HasMedicalNeeds")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCheckedOut")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NeedsSpecialAssistance")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ShelterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpecialRequirements")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsCheckedOut")
                        .HasDatabaseName("IX_ShelterCheckIns_IsCheckedOut");

                    b.HasIndex("ShelterId")
                        .HasDatabaseName("IX_ShelterCheckIns_ShelterId");

                    b.ToTable("ShelterCheckIns");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.SmsNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DisasterAlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisasterIncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TwilioMessageSid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DisasterAlertId");

                    b.HasIndex("DisasterIncidentId");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_SmsNotifications_PhoneNumber");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("IX_SmsNotifications_SentAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_SmsNotifications_Status");

                    b.HasIndex("UserId");

                    b.ToTable("SmsNotifications");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.SmsTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TemplateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_SmsTemplates_Type");

                    b.HasIndex("LanguageCode", "Type")
                        .HasDatabaseName("IX_SmsTemplates_Language_Type");

                    b.ToTable("SmsTemplates");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("LGAId")
                        .HasColumnType("int");

                    b.Property<string>("LGAName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_Users_CityId");

                    b.HasIndex("LGAId")
                        .HasDatabaseName("IX_Users_LGAId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.UssdSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContextData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LGAId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserInput")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_UssdSessions_IsActive");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("IX_UssdSessions_LastActivityAt");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("IX_UssdSessions_PhoneNumber");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_UssdSessions_SessionId");

                    b.ToTable("UssdSessions");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.VoiceCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CallSid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CallType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid?>("DisasterAlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisasterIncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("MenuState")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordingDuration")
                        .HasColumnType("int");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RingingAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ToPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserInput")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CallSid")
                        .IsUnique()
                        .HasDatabaseName("IX_VoiceCalls_CallSid")
                        .HasFilter("[CallSid] IS NOT NULL");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_VoiceCalls_CreatedAt");

                    b.HasIndex("DisasterAlertId")
                        .HasDatabaseName("IX_VoiceCalls_DisasterAlertId");

                    b.HasIndex("DisasterIncidentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_VoiceCalls_Status");

                    b.HasIndex("ToPhoneNumber")
                        .HasDatabaseName("IX_VoiceCalls_ToPhoneNumber");

                    b.HasIndex("UserId");

                    b.ToTable("VoiceCalls");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WaterLevelReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AlertTriggered")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AlertTriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCalibrated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<double>("Level")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("RateOfChange")
                        .HasColumnType("float");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("IX_WaterLevelReadings_SensorId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_WaterLevelReadings_Timestamp");

                    b.HasIndex("SensorId", "Timestamp")
                        .HasDatabaseName("IX_WaterLevelReadings_SensorId_Timestamp");

                    b.ToTable("WaterLevelReadings");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WaterLevelSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Accuracy")
                        .HasColumnType("float");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlertRecipients")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("CriticalLevel")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentLevel")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CurrentReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<double>("DangerLevel")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LGAId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCommunicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastDataReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("MaxMeasurableLevel")
                        .HasColumnType("float");

                    b.Property<double>("MinMeasurableLevel")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("NormalLevel")
                        .HasColumnType("float");

                    b.Property<int>("PowerSource")
                        .HasColumnType("int");

                    b.Property<int>("SensorType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("WarningLevel")
                        .HasColumnType("float");

                    b.Property<string>("WaterBodyName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("WaterBodyType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("IX_WaterLevelSensors_DeviceId");

                    b.HasIndex("LGAId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WaterLevelSensors_Status");

                    b.HasIndex("CityId", "Status")
                        .HasDatabaseName("IX_WaterLevelSensors_CityId_Status");

                    b.ToTable("WaterLevelSensors");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WeatherReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CloudCover")
                        .HasColumnType("int");

                    b.Property<int?>("Condition")
                        .HasColumnType("int");

                    b.Property<double?>("DewPoint")
                        .HasColumnType("float");

                    b.Property<double?>("FeelsLike")
                        .HasColumnType("float");

                    b.Property<double?>("Humidity")
                        .HasColumnType("float");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double?>("Pressure")
                        .HasColumnType("float");

                    b.Property<double?>("Rainfall")
                        .HasColumnType("float");

                    b.Property<double?>("SeaLevelPressure")
                        .HasColumnType("float");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("SolarRadiation")
                        .HasColumnType("float");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<double?>("UVIndex")
                        .HasColumnType("float");

                    b.Property<double?>("Visibility")
                        .HasColumnType("float");

                    b.Property<double?>("WindDirection")
                        .HasColumnType("float");

                    b.Property<string>("WindDirectionCardinal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("WindGust")
                        .HasColumnType("float");

                    b.Property<double?>("WindSpeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("IX_WeatherReadings_SensorId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_WeatherReadings_Timestamp");

                    b.HasIndex("SensorId", "Timestamp")
                        .HasDatabaseName("IX_WeatherReadings_SensorId_Timestamp");

                    b.ToTable("WeatherReadings");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WeatherSensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AlertRecipients")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AlertsEnabled")
                        .HasColumnType("bit");

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("CurrentHumidity")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentPressure")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CurrentReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("CurrentTemperature")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentWindDirection")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentWindSpeed")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasHumiditySensor")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPressureSensor")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRainGauge")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTemperatureSensor")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWindSensor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LGAId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastCommunicationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastDataReceivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PowerSource")
                        .HasColumnType("int");

                    b.Property<int>("SensorType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique()
                        .HasDatabaseName("IX_WeatherSensors_DeviceId");

                    b.HasIndex("LGAId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WeatherSensors_Status");

                    b.HasIndex("CityId", "Status")
                        .HasDatabaseName("IX_WeatherSensors_CityId_Status");

                    b.ToTable("WeatherSensors");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WhatsAppMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConversationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid?>("DisasterAlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DisasterIncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromPhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("InReplyToMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MediaContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageSid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MessageType")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TemplateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateParameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("IX_WhatsAppMessages_ConversationId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_WhatsAppMessages_CreatedAt");

                    b.HasIndex("DisasterAlertId");

                    b.HasIndex("DisasterIncidentId");

                    b.HasIndex("MessageSid")
                        .IsUnique()
                        .HasDatabaseName("IX_WhatsAppMessages_MessageSid")
                        .HasFilter("[MessageSid] IS NOT NULL");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WhatsAppMessages_Status");

                    b.HasIndex("ToPhoneNumber")
                        .HasDatabaseName("IX_WhatsAppMessages_ToPhoneNumber");

                    b.HasIndex("UserId");

                    b.ToTable("WhatsAppMessages");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.City", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.LGA", "LGA")
                        .WithMany("Cities")
                        .HasForeignKey("LGAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.CityFloodPrediction", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.City", null)
                        .WithMany("Predictions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.CsvFileCity", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.CsvFile", null)
                        .WithMany("CsvFileCities")
                        .HasForeignKey("CsvFileId");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.DeviceToken", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.DisasterAlert", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.DisasterIncident", "RelatedIncident")
                        .WithMany()
                        .HasForeignKey("RelatedIncidentId");

                    b.Navigation("RelatedIncident");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.DisasterIncident", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("GlobalDisasterManagement.Models.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId");

                    b.HasOne("GlobalDisasterManagement.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("LGA");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.DisasterResource", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.EmergencyShelter", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("GlobalDisasterManagement.Models.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId");

                    b.Navigation("City");

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.EvacuationRoute", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("GlobalDisasterManagement.Models.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId");

                    b.Navigation("City");

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.PushNotification", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.DisasterAlert", "DisasterAlert")
                        .WithMany()
                        .HasForeignKey("DisasterAlertId");

                    b.HasOne("GlobalDisasterManagement.Models.DisasterIncident", "DisasterIncident")
                        .WithMany()
                        .HasForeignKey("DisasterIncidentId");

                    b.Navigation("DisasterAlert");

                    b.Navigation("DisasterIncident");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.RainfallReading", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.RainfallSensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.RainfallSensor", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("GlobalDisasterManagement.Models.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId");

                    b.Navigation("City");

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.ShelterCheckIn", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.EmergencyShelter", "Shelter")
                        .WithMany("CheckIns")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.SmsNotification", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.DisasterAlert", "DisasterAlert")
                        .WithMany()
                        .HasForeignKey("DisasterAlertId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlobalDisasterManagement.Models.DisasterIncident", "DisasterIncident")
                        .WithMany()
                        .HasForeignKey("DisasterIncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GlobalDisasterManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("DisasterAlert");

                    b.Navigation("DisasterIncident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.VoiceCall", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.DisasterAlert", "DisasterAlert")
                        .WithMany()
                        .HasForeignKey("DisasterAlertId");

                    b.HasOne("GlobalDisasterManagement.Models.DisasterIncident", "DisasterIncident")
                        .WithMany()
                        .HasForeignKey("DisasterIncidentId");

                    b.HasOne("GlobalDisasterManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("DisasterAlert");

                    b.Navigation("DisasterIncident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WaterLevelReading", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.WaterLevelSensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WaterLevelSensor", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("GlobalDisasterManagement.Models.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId");

                    b.Navigation("City");

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WeatherReading", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.WeatherSensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WeatherSensor", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("GlobalDisasterManagement.Models.LGA", "LGA")
                        .WithMany()
                        .HasForeignKey("LGAId");

                    b.Navigation("City");

                    b.Navigation("LGA");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WhatsAppMessage", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.DisasterAlert", "DisasterAlert")
                        .WithMany()
                        .HasForeignKey("DisasterAlertId");

                    b.HasOne("GlobalDisasterManagement.Models.DisasterIncident", "DisasterIncident")
                        .WithMany()
                        .HasForeignKey("DisasterIncidentId");

                    b.HasOne("GlobalDisasterManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("DisasterAlert");

                    b.Navigation("DisasterIncident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalDisasterManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GlobalDisasterManagement.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.City", b =>
                {
                    b.Navigation("Predictions");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.CsvFile", b =>
                {
                    b.Navigation("CsvFileCities");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.EmergencyShelter", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.LGA", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.RainfallSensor", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WaterLevelSensor", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("GlobalDisasterManagement.Models.WeatherSensor", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
